version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "17:00"
    target-branch: "dev"

  # Temporarily disable Dependabot for Dart pub, not really useful for now
  # Maintain dependencies for Dart pub
  # - package-ecosystem: "pub"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "saturday"
  #     time: "17:00"
  #   target-branch: "dev"
  #   open-pull-requests-limit: 5

