version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "dependabot"
    reviewers:
      - "khoadn"
    commit-message:
      prefix: "chore: "

  # Maintain dependencies for Dart pub
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
