name: boorusama
description: A mobile client for Booru sites.

publish_to: "none"
version: 3.21.1+118

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  android_intent_plus: ^5.1.0
  animated_list_plus: ^0.5.2
  background_downloader: ^8.5.6
  bitsdojo_window: ^0.1.6
  cached_network_image: ^3.4.1
  chewie: ^1.8.5
  clock: ^1.1.1
  collection: ^1.17.0
  connectivity_plus: ^6.0.5
  context_menus:
    git:
      url: https://github.com/khoadng/flutter-context-menu.git
      ref: 7a310fa2aacfaa95339ee2535f0797fcf84efeca
  cookie_jar: ^4.0.8
  crypto: ^3.0.5
  custom_sliding_segmented_control: ^1.8.3
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dio_http2_adapter: ^2.5.3
  dropdown_button2: ^2.3.9
  dynamic_color: ^1.7.0
  easy_localization: ^3.0.7
  easy_logger: ^0.0.2
  equatable: ^2.0.5
  expandable: ^5.0.1
  exprollable_page_view: ^1.0.1
  extended_image: ^8.3.1
  fast_immutable_collections: ^10.2.4
  file_picker: ^8.0.7
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_performance: ^0.10.0+8
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_html: ^3.0.0-beta.2
  flutter_improved_scrolling: ^0.0.3
  flutter_local_notifications: ^17.2.3
  flutter_markdown: ^0.7.3+2
  flutter_portal: ^1.1.4
  flutter_riverpod: ^2.5.1
  flutter_scatter: ^0.2.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html_core: ^0.15.2
  font_awesome_flutter: ^10.7.0
  fpdart: ^1.1.0
  fvp: ^0.26.1
  gal: ^2.3.0
  go_router: ^14.3.0
  hive: ^2.2.3
  html: ^0.15.4
  http: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  jiffy: ^6.2.1
  like_button: ^2.0.5
  local_auth: ^2.3.0
  lottie: ^3.1.2
  material_symbols_icons: ^4.2785.1
  media_scanner: ^2.1.0
  modal_bottom_sheet: ^3.0.0-pre
  multi_split_view: ^3.5.0
  oktoast: ^3.4.0
  package_info_plus: ^8.0.2
  path: ^1.8.3
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  petitparser: ^6.0.2
  photo_view: ^0.15.0
  rate_my_app: 1.1.4 # DO NOT UPDATE, 2.0.0 is adding unnecessary permissions
  readmore: ^3.0.0
  recase: ^4.1.0
  reorderable_grid_view: ^2.2.8
  reorderables:
    git:
      url: https://github.com/khoadng/reorderables.git
      ref: 69d1b8b272f3b77dc6a6b7399fa8931cdd660d77
  rich_text_controller: ^1.4.2
  rxdart: ^0.28.0
  scroll_to_index: ^3.0.1
  searchfield: ^1.1.6
  share_handler: ^0.0.20
  share_plus: ^10.0.2
  sliver_tools: ^0.2.12
  stack_trace: ^1.11.0
  timeago: ^3.7.0
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  version: ^3.0.2
  video_player: ^2.9.2
  webview_cookie_manager:
    git:
       url: https://github.com/fryette/webview_cookie_manager
       ref: 923e514752ad7bb7e83849f11de767a301ac57b5
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.16.8
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons:
    git: https://github.com/fluttercommunity/flutter_launcher_icons.git
  flutter_lints: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  import_sorter: ^4.6.0
  mocktail: ^1.0.4
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icon/
    - assets/images/
    - assets/translations/
    - assets/information.json
    - assets/tagdef.json
    - assets/ca/isrgrootx1.pem
    - boorus.yaml
    - CHANGELOG.md
