name: boorusama
description: A mobile client for Danbooru.

publish_to: "none"
version: 2.8.0+38

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  android_intent_plus: ^3.1.1+1
  animated_flip_counter: ^0.2.5
  animated_list_plus: ^0.4.4
  basic_utils: ^5.4.2
  bitsdojo_window: ^0.1.2
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  chewie: ^1.3.5
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  cross_file: ^0.3.3+2
  device_info_plus: ^8.0.0
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  file_picker: ^5.2.1
  filesize: ^2.0.1
  fluro: ^2.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  flutter_cache_manager: ^3.3.0
  flutter_downloader:
    git:
      url: https://github.com/khoadng/flutter_downloader.git
      ref: master
  flutter_hooks: ^0.18.4
  flutter_html:
    git:
      url: https://github.com/khoadng/flutter_html.git
      ref: fix-rebuild
  flutter_improved_scrolling: ^0.0.3
  flutter_local_notifications: ^12.0.4
  flutter_markdown: ^0.6.13
  flutter_portal: ^1.1.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_tags_x: ^1.1.0
  font_awesome_flutter: ^10.3.0
  hive: ^2.2.3
  html: ^0.15.0
  image_gallery_saver: ^1.7.1
  intl: ^0.17.0
  jiffy: ^5.0.0
  like_button: ^2.0.5
  lottie: ^2.0.0
  media_scanner: ^2.1.0
  modal_bottom_sheet: ^2.1.1
  number_inc_dec:
    git:
      url: https://github.com/hilalbaig/number_inc_dec.git
      ref: f66ee872727172ce2fe57f118d569339d54c384d
  package_info_plus: ^3.0.2
  page_transition: ^2.0.9
  path: ^1.8.2
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  permission_handler: ^10.0.1
  photo_view: ^0.14.0
  pull_to_refresh:
    git:
      url: https://github.com/khoadng/flutter_pulltorefresh.git
      ref: flutter-3.0
  quiver: ^3.1.0
  rate_my_app: ^1.1.3
  recase: ^4.0.0
  retrofit: ^3.3.1
  rich_text_controller:
    git:
      url: https://github.com/khoadng/rich_text_controller.git
      ref: flutter-3.0
  rxdart: ^0.27.7
  scroll_to_index: ^3.0.1
  sentry_flutter: ^6.15.1
  share_plus: ^6.3.0
  timeago: ^3.3.0
  toggle_switch: ^2.0.1
  tuple: ^2.0.0
  url_launcher: ^6.1.5
  video_player: ^2.4.8
  webview_flutter: ^3.0.4

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  import_sorter: ^4.6.0
  mocktail: ^0.3.0
  retrofit_generator: ^4.0.1
  test: ^1.21.1

flutter_icons:
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/icon/icon-512x512.png"
  adaptive_icon_background: "#e7bf55"
  android: true
  ios: true
  image_path: "assets/icon/icon-512x512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icon/
    - assets/images/
    - assets/translations/
    - assets/information.json
    - assets/tagdef.json
    - assets/boorus.json
    - CHANGELOG.md
