name: boorusama
description: A mobile client for Booru sites.

publish_to: "none"
version: 3.22.8+135

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - packages/foundation
  - packages/booru_clients
  - packages/filename_generator
  - packages/flutter_staggered_grid_view
  - packages/extended_image

dependencies:
  # local packages
  foundation:
    path: packages/foundation
  booru_clients:
    path: packages/booru_clients
  filename_generator:
    path: packages/filename_generator
  flutter_staggered_grid_view:
    path: packages/flutter_staggered_grid_view
  extended_image:
    path: packages/extended_image

  android_intent_plus: ^5.1.0
  animated_list_plus: ^0.5.2
  background_downloader: ^8.8.0
  bonsoir: ^5.1.10
  collection: ^1.17.0
  connectivity_plus: ^6.1.0
  context_menus:
    git:
      url: https://github.com/khoadng/flutter-context-menu.git
      ref: 7a310fa2aacfaa95339ee2535f0797fcf84efeca
  cookie_jar: ^4.0.8
  crypto: ^3.0.5
  device_info_plus: ^11.1.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dio_http2_adapter: ^2.5.3
  dropdown_button2: ^2.3.9
  dynamic_color: ^1.7.0
  equatable: ^2.0.5
  expandable: ^5.0.1
  fast_immutable_collections: ^11.0.0
  file_picker: 8.1.4
  firebase_analytics: ^11.3.5
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_performance: ^0.10.0+10
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_improved_scrolling: ^0.0.3
  flutter_local_notifications: ^18.0.1
  flutter_markdown: ^0.7.3+2
  flutter_portal: ^1.1.4
  flutter_riverpod: ^2.5.1
  flutter_scatter: ^0.2.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html_core: ^0.15.2
  font_awesome_flutter: ^10.7.0
  fvp:
    git:
      url: https://github.com/wang-bin/fvp.git
      ref: 7090c3a926b295747cccb1333895417ab8a85584
  gal: ^2.3.0
  go_router: ^14.3.0
  hive: ^2.2.3
  html: ^0.15.4
  http: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  like_button: ^2.0.5
  local_auth: ^2.3.0
  lottie: ^3.1.2
  material_symbols_icons: ^4.2785.1
  modal_bottom_sheet: ^3.0.0-pre
  multi_split_view: ^3.5.0
  native_dio_adapter: 1.3.0 # 1.4.0 introduces cupertino_http 2.0.0 which causes hangs on iOS
  oktoast: ^3.4.0
  package_info_plus: ^8.0.2
  path: ^1.8.3
  path_drawing: ^1.0.1
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  petitparser: ^6.0.2
  rate_my_app: ^2.2.0
  readmore: ^3.0.0
  reorderable_grid_view: ^2.2.8
  reorderables:
    git:
      url: https://github.com/khoadng/reorderables.git
      ref: 69d1b8b272f3b77dc6a6b7399fa8931cdd660d77
  rich_text_controller: ^1.4.2
  rxdart: ^0.28.0
  scroll_to_index: ^3.0.1
  searchfield: ^1.2.1
  share_handler: ^0.0.20
  share_plus: ^10.0.2
  shelf: ^1.4.1
  sliver_tools: ^0.2.12
  smooth_page_indicator: ^1.1.0
  socks5_proxy: ^2.0.0
  stack_trace: ^1.11.0
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  version: ^3.0.2
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  webview_cookie_manager:
    git:
       url: https://github.com/khoadng/webview_cookie_manager
       ref: 8572dd54c437c919aedc8dca6c5bffd25fe74b3c
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0
  window_manager: ^0.4.3
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons:
    git: https://github.com/fluttercommunity/flutter_launcher_icons.git
  flutter_lints: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  import_sorter: ^4.6.0
  mocktail: ^1.0.4
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icon/
    - assets/images/
    - assets/translations/
    - assets/information.json
    - assets/tagdef.json
    - assets/ca/isrgrootx1.pem
    - boorus.yaml
    - CHANGELOG.md
