name: boorusama
description: A mobile client for Danbooru.

publish_to: "none" 
version: 1.0.7+12

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.3
  auto_size_text: ^3.0.0
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  chewie: ^1.3.3
  connectivity_plus: ^2.3.3
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  filesize: ^2.0.1
  fluro: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_datetime_picker: ^1.5.1
  flutter_downloader: ^1.8.0+1
  flutter_hooks: ^0.18.4
  flutter_html: ^3.0.0-alpha.5
  flutter_inappwebview: ^5.4.3+7
  flutter_portal: ^1.1.0
  flutter_tags_x: ^1.1.0
  font_awesome_flutter: ^10.1.0
  hive: ^2.2.2
  hooks_riverpod: ^1.0.4
  http: ^0.13.4
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  lottie: ^1.3.0
  mockito: ^5.2.0
  modal_bottom_sheet: ^2.0.1
  number_inc_dec: ^0.8.0
  package_info_plus: ^1.4.2
  path: ^1.8.1
  path_provider: ^2.0.11
  permission_handler: ^9.2.0
  photo_view: ^0.14.0
  popup_menu:
    git:
      url: https://github.com/chinabrant/popup_menu.git
      ref: master
  pull_to_refresh: ^2.0.0
  quiver: ^3.1.0
  recase: ^4.0.0
  retrofit: ^3.0.1+1
  rxdart: ^0.27.4
  scroll_to_index: ^3.0.1
  sentry_flutter: ^6.5.1
  settings_ui: ^2.0.2
  share_plus: ^4.0.7
  shared_preferences: ^2.0.15
  sliding_up_panel:
    git:
      url: https://github.com/khoadng/sliding_up_panel.git
      ref: custom-scroll-controller
  timeago: ^3.2.2
  tuple: ^2.0.0
  url_launcher: ^6.1.3
  webview_flutter: ^3.0.4
  html: ^0.15.0
  collection: ^1.16.0
  video_player: ^2.4.4
  toggle_switch: ^2.0.1

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0
  retrofit_generator: ^4.0.1
  test: ^1.21.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icon/
    - assets/translations/
    - assets/information.json