name: boorusama
description: A mobile client for Danbooru.

publish_to: "none"
version: 3.3.3+61

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  android_intent_plus: ^4.0.2
  animated_flip_counter: ^0.2.5
  animated_list_plus: ^0.5.0
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.5
  cached_network_image:
    git:
      url: https://github.com/SuaMusica/flutter_cached_network_image.git
      ref: feature/errorListener
      path: cached_network_image
  carousel_slider: ^4.2.1
  chewie: ^1.4.0
  collection: ^1.17.0
  connectivity_plus: ^4.0.0
  context_menus:
    git:
      url: https://github.com/khoadng/flutter-context-menu.git
      ref: e0ee29b44156afa167d8328299e00486d2787b4b
  crypto: ^3.0.2
  device_info_plus: ^8.2.2
  dio: ^5.3.2
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  dio_http2_adapter: ^2.3.1+1
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  exprollable_page_view: ^1.0.0-rc.1
  fast_immutable_collections: ^9.1.5
  file_picker: ^5.2.5
  filesize: ^2.0.1
  firebase_analytics: ^10.4.3
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_download_manager:
    git:
      url: https://github.com/khoadng/flutter_download_manager.git
      ref: dio
  flutter_html:
    git:
      url: https://github.com/khoadng/flutter_html.git
      ref: fix-rebuild
  flutter_improved_scrolling: ^0.0.3
  flutter_local_notifications: ^15.1.0+1
  flutter_markdown: ^0.6.17+1
  flutter_portal: ^1.1.4
  flutter_riverpod: ^2.3.7
  flutter_scatter: ^0.2.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_tags_x: ^1.1.0
  font_awesome_flutter: ^10.5.0
  fpdart: ^1.1.0
  go_router: ^10.1.0
  hive: ^2.2.3
  html: ^0.15.4
  http: ^0.13.6
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.0
  jiffy: ^6.2.1
  like_button: ^2.0.5
  lottie: ^2.6.0
  media_scanner: ^2.1.0
  modal_bottom_sheet: ^3.0.0-pre
  number_inc_dec:
    git:
      url: https://github.com/hilalbaig/number_inc_dec.git
      ref: f66ee872727172ce2fe57f118d569339d54c384d
  oktoast: ^3.3.1
  package_info_plus: ^3.1.2
  page_transition: ^2.0.9
  path: ^1.8.3
  path_provider: ^2.1.0
  percent_indicator: ^4.2.3
  permission_handler: ^10.4.3
  petitparser: ^5.4.0
  photo_view: ^0.14.0
  pull_to_refresh:
    git:
      url: https://github.com/khoadng/flutter_pulltorefresh.git
      ref: flutter-3.0
  rate_my_app: ^2.0.0
  recase: ^4.1.0
  reorderable_grid_view: ^2.2.7
  reorderables:
    git:
      url: https://github.com/khoadng/reorderables.git
      ref: 69d1b8b272f3b77dc6a6b7399fa8931cdd660d77
  retrofit: ^4.0.1
  rich_text_controller:
    git:
      url: https://github.com/khoadng/rich_text_controller.git
      ref: flutter-3.0
  riverpod_infinite_scroll: ^1.0.9
  rxdart: ^0.27.7
  scroll_to_index: ^3.0.1
  share_handler: ^0.0.17
  share_plus: ^6.3.4
  sliver_tools: ^0.2.10
  stack_trace: ^1.11.0
  timeago: ^3.5.0
  toggle_switch: ^2.1.0
  url_launcher: ^6.1.12
  version: ^3.0.2
  video_player: ^2.7.0
  video_player_macos: ^2.0.1
  video_player_win: ^2.2.2
  webview_flutter: ^4.2.3
  xml: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  import_sorter: ^4.6.0
  mocktail: ^1.0.0
  retrofit_generator: ^7.0.8
  test: ^1.21.1

flutter_icons:
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/icon/icon-512x512.png"
  adaptive_icon_background: "#e7bf55"
  android: true
  ios: true
  image_path: "assets/icon/icon-512x512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icon/
    - assets/images/
    - assets/translations/
    - assets/information.json
    - assets/tagdef.json
    - assets/boorus.json
    - assets/booru_salts.json
    - CHANGELOG.md
