name: boorusama
description: A mobile client for Danbooru.

publish_to: "none"
version: 3.13.1+93

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  android_intent_plus: ^4.0.3
  animated_list_plus: ^0.5.2
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.6
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  chewie: ^1.7.1
  clock: ^1.1.1
  collection: ^1.17.0
  connectivity_plus: ^5.0.1
  context_menus:
    git:
      url: https://github.com/khoadng/flutter-context-menu.git
      ref: 314d1871b50d5376fa6fa30b81d7279a3734d018
  crypto: ^3.0.3
  custom_sliding_segmented_control: ^1.8.1
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dio_http2_adapter: ^2.4.0
  dynamic_color: ^1.6.9
  easy_localization: ^3.0.4
  equatable: ^2.0.5
  expandable: ^5.0.1
  exprollable_page_view: ^1.0.0-rc.2
  extended_image: ^8.2.0
  fast_immutable_collections: ^10.1.1
  file_picker: ^6.1.1
  filesize: ^2.0.1
  firebase_analytics: ^10.8.5
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.14
  firebase_performance: ^0.9.3+13
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_advanced_segment: ^3.0.2
  flutter_cache_manager: ^3.3.1
  flutter_download_manager:
    git:
      url: https://github.com/khoadng/flutter_download_manager.git
      ref: 2e2f17a2e9ba95dbbbcd9b7c6c5ebfabda8123df
  flutter_html:
    git:
      url: https://github.com/khoadng/flutter_html.git
      ref: fix-rebuild
  flutter_improved_scrolling: ^0.0.3
  flutter_local_notifications: ^16.3.2
  flutter_markdown: ^0.6.19
  flutter_portal: ^1.1.4
  flutter_riverpod: ^2.4.10
  flutter_scatter: ^0.2.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_tags_x: ^1.1.0
  font_awesome_flutter: ^10.7.0
  fpdart: ^1.1.0
  fvp: ^0.14.0
  gal: ^2.3.0
  go_router: ^13.2.0
  hive: ^2.2.3
  html: ^0.15.4
  http: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.1
  jiffy: ^6.2.1
  like_button: ^2.0.5
  local_auth: ^2.1.8
  lottie: ^3.0.0
  material_symbols_icons: ^4.2713.0
  media_scanner: ^2.1.0
  modal_bottom_sheet: ^3.0.0-pre
  multi_split_view: ^2.4.0
  number_inc_dec:
    git:
      url: https://github.com/hilalbaig/number_inc_dec.git
      ref: f66ee872727172ce2fe57f118d569339d54c384d
  oktoast: ^3.4.0
  package_info_plus: ^5.0.1
  page_transition: ^2.1.0
  path: ^1.8.3
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.0
  petitparser: ^6.0.2
  photo_view: ^0.14.0
  rate_my_app: ^1.1.4
  recase: ^4.1.0
  reorderable_grid_view: ^2.2.8
  reorderables:
    git:
      url: https://github.com/khoadng/reorderables.git
      ref: 69d1b8b272f3b77dc6a6b7399fa8931cdd660d77
  rich_text_controller:
    git:
      url: https://github.com/khoadng/rich_text_controller.git
      ref: flutter-3.0
  riverpod_infinite_scroll: ^1.0.9
  rxdart: ^0.27.7
  scroll_to_index: ^3.0.1
  searchfield: ^0.9.2
  share_handler: ^0.0.20
  share_plus: ^7.2.2
  sliver_tools: ^0.2.12
  stack_trace: ^1.11.0
  timeago: ^3.6.1
  url_launcher: ^6.2.4
  uuid: ^4.3.3
  version: ^3.0.2
  video_player: ^2.8.2
  video_player_macos: ^2.0.1
  video_player_win: ^2.3.4
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.15.0
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons:
    git: https://github.com/fluttercommunity/flutter_launcher_icons.git
  flutter_lints: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  import_sorter: ^4.6.0
  mocktail: ^1.0.1
  test: ^1.21.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icon/
    - assets/images/
    - assets/translations/
    - assets/information.json
    - assets/tagdef.json
    - assets/ca/isrgrootx1.pem
    - boorus.yaml
    - CHANGELOG.md
