name: boorusama
description: A mobile client for Danbooru.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+8

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  chewie: ^1.2.2
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.4
  curved_navigation_bar: ^1.0.3
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  filesize: ^2.0.1
  fluro: ^2.0.3
  flutter_datetime_picker: ^1.5.1
  flutter_downloader: ^1.7.4
  flutter_hooks: ^0.16.0
  flutter_html: ^2.1.5
  flutter_inappwebview: ^5.3.2
  flutter_portal: ^0.4.0
  flutter_tags: ^1.0.0-nullsafety.1
  font_awesome_flutter: ^10.1.0
  hive: ^2.2.1
  hooks_riverpod: 0.13.1+1
  http: ^0.13.3
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.4
  lottie: ^1.2.2
  modal_bottom_sheet: ^2.0.1
  number_inc_dec: ^0.8.0
  path: ^1.8.0
  path_provider: ^2.0.4
  permission_handler: ^8.1.6
  photo_view: ^0.14.0
  popup_menu:
    git:
      url: https://github.com/chinabrant/popup_menu.git
      ref: master
  pull_to_refresh: ^2.0.0
  recase: ^4.0.0
  retrofit: ^2.2.0
  scroll_to_index: ^2.1.1
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.7
  sliding_up_panel: ^2.0.0+1
  timeago: ^3.2.2
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  mockito: ^5.0.15
  flutter_bloc: ^8.0.1
  webview_flutter: ^2.8.0
  url_launcher: ^6.1.2
  share_plus: ^4.0.6
  flutter_cache_manager: ^3.3.0
  sentry_flutter: ^6.5.1
  firebase_analytics: ^9.1.1
  firebase_performance: ^0.8.0+6
  package_info_plus: ^1.4.2
  quiver: ^3.1.0
  tuple: ^2.0.0
  rxdart: ^0.27.4

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  import_sorter: ^4.6.0
  retrofit_generator: ^2.0.1
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.1.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icon/
    - assets/translations/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
