name: boorusama
description: A mobile client for Booru sites.

publish_to: "none"
version: 4.1.5+164

environment:
  sdk: ^3.8.1

workspace:
  - packages/foundation
  - packages/booru_clients
  - packages/filename_generator
  - packages/sliver_masonry_grid
  - packages/extended_image
  - packages/flutter_sqlite3_migration
  - packages/retriable
  - packages/rich_text_controller
  - packages/i18n
  - packages/codegen

dependencies:
  # local packages
  foundation:
    path: packages/foundation
  i18n:
    path: packages/i18n
  booru_clients:
    path: packages/booru_clients
  filename_generator:
    path: packages/filename_generator
  sliver_masonry_grid:
    path: packages/sliver_masonry_grid
  extended_image:
    path: packages/extended_image
  flutter_sqlite3_migration:
    path: packages/flutter_sqlite3_migration
  retriable:
    path: packages/retriable
  rich_text_controller:
    path: packages/rich_text_controller

  android_intent_plus: ^5.1.0
  archive: ^4.0.7
  animated_list_plus: ^0.5.2
  background_downloader: ^9.1.1
  bonsoir: ^5.1.11
  collection: ^1.17.0
  connectivity_plus: ^6.1.0
  context_menus:
    git:
      url: https://github.com/khoadng/flutter-context-menu.git
      ref: 3e46518ea7823aebae8838754c21353bd2d44189
  cookie_jar: ^4.0.8
  cross_file: ^0.3.4+2
  crypto: ^3.0.5
  device_info_plus: ^11.1.0
  dio: ^5.7.0
  dio_http2_adapter: ^2.5.3
  dropdown_button2: ^2.3.9
  dynamic_color: ^1.7.0
  equatable: ^2.0.5
  expandable: ^5.0.1
  fast_immutable_collections: ^11.0.0
  file_picker: ^10.2.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_improved_scrolling: ^0.0.3
  flutter_local_notifications: ^19.2.1
  flutter_markdown: ^0.7.3+2
  flutter_portal: ^1.1.4
  flutter_riverpod: ^2.5.1
  flutter_scatter: ^0.2.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html_core: ^0.16.0
  font_awesome_flutter: ^10.7.0
  fvp: ^0.33.0
  gal: ^2.3.0
  go_router: ^16.0.0
  google_api_availability: ^5.0.0
  hive: ^2.2.3
  html: ^0.15.4
  http: ^1.1.0
  infinite_scroll_pagination: ^5.1.0
  intl: ^0.20.2
  like_button: ^2.0.5
  local_auth: ^2.3.0
  lottie: ^3.1.2
  material_symbols_icons: ^4.2785.1
  modal_bottom_sheet: ^3.0.0-pre
  multi_split_view: ^3.5.0
  native_dio_adapter: ^1.4.0
  oktoast: ^3.4.0
  package_info_plus: ^8.0.2
  pasteboard: ^0.4.0
  path: ^1.8.3
  path_drawing: ^1.0.1
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  permission_handler: ^12.0.0+1
  petitparser: ^6.0.2
  purchases_flutter: ^8.4.1
  rate_my_app: ^2.2.0
  readmore: ^3.0.0
  reorderable_grid_view: ^2.2.8
  reorderables:
    git:
      url: https://github.com/khoadng/reorderables.git
      ref: 69d1b8b272f3b77dc6a6b7399fa8931cdd660d77
  rxdart: ^0.28.0
  scroll_to_index: ^3.0.1
  searchfield:
    git:
      url: https://github.com/khoadng/searchfield.git
      ref: fix-highlight-null-2
  share_handler: ^0.0.20
  share_plus: ^11.0.0
  shelf: ^1.4.1
  selection_mode:
    git:
      url: https://github.com/khoadng/selection_mode.git
      ref: 14d636de979280b2cb141e63713f27eac16c1b54
  sliver_tools: ^0.2.12
  smooth_page_indicator: ^1.1.0
  socks5_proxy: ^2.0.0
  sqlite3: ^2.7.2
  sqlite3_flutter_libs: ^0.5.29+1
  stack_trace: ^1.11.0
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  version: ^3.0.2
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  webview_cookie_manager:
    git:
       url: https://github.com/khoadng/webview_cookie_manager
       ref: 8572dd54c437c919aedc8dca6c5bffd25fe74b3c
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0
  window_manager: 0.4.3 # https://github.com/leanflutter/window_manager/issues/550
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons:
    git: https://github.com/fluttercommunity/flutter_launcher_icons.git
  flutter_lints: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  import_sorter: ^4.6.0
  mocktail: ^1.0.4
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icon/
    - assets/images/
    - assets/information.json
    - assets/tagdef.json
    - assets/ca/isrgrootx1.pem
    - boorus.yaml
    - CHANGELOG.md
