name: boorusama
description: A mobile client for Danbooru.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  auto_size_text: ^2.1.0
  cached_network_image: ^2.3.3
  carousel_slider: ^3.0.0
  chewie: ^0.12.2
  connectivity_plus: ^0.8.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^0.3.7
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  filesize: ^1.0.4
  fluro: ^2.0.3
  flutter_datetime_picker: ^1.4.0
  flutter_downloader: ^1.5.1
  flutter_hooks: ^0.16.0
  flutter_html: ^1.0.2
  flutter_inappwebview: ^5.1.0
  flutter_portal: ^0.3.0
  flutter_tags: ^0.4.9
  font_awesome_flutter: ^8.11.0
  freezed_annotation: ^0.12.0
  hive: ^1.4.4+1
  hooks_riverpod: ^0.12.2
  http: ^0.12.2
  intl: ^0.17.0
  jiffy: ^4.0.0
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  lottie: ^0.7.0+1
  meta: ^1.2.3
  # mockito: ^4.1.4
  modal_bottom_sheet: ^1.0.0+1
  number_inc_dec: ^0.6.6
  path: ^1.7.0
  path_provider: ^1.6.18
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.2
  popup_menu: ^1.0.5
  pull_to_refresh: ^1.6.2
  recase: ^3.0.1
  retrofit: ^1.3.4+1
  scroll_to_index: ^2.0.0
  settings_ui: ^0.6.0
  shared_preferences: ^0.5.12+4
  sliding_up_panel: ^1.0.2

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.2
  import_sorter: ^4.4.1
  retrofit_generator: ^1.4.1+1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icon/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
