name: extended_image
description: Custom image widget for Boorusama.
publish_to: 'none' 

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.7
  extended_image_library: ^4.0.1
  flutter:
    sdk: flutter
  flutter_avif:
    git:
      url: https://github.com/khoadng/flutter_avif.git
      ref: 785323f3dbf720a4d184595c393cf416aa39c645
      path: flutter_avif
  path: ^1.8.3
  path_provider: ^2.1.2
  retriable:
    path: ../retriable

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
