name: retriable
description: A Dart package for handling retries with configurable strategies
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dio: ^5.0.0
  http_client_helper: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
