name: booru_clients
description: Clients for various Booru sites.
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  collection: ^1.17.0
  dio: ^5.7.0
  equatable: ^2.0.7
  graphql_flutter: ^5.2.1
  html: ^0.15.4
  intl: ^0.20.2
  path: ^1.8.3
  version: ^3.0.2
  xml: ^6.5.0

dev_dependencies:
  codegen:
    path: ../codegen
  lints: ^6.0.0
  shelf: ^1.4.2
  test: ^1.25.15
  yaml: ^3.1.2
