name: flutter_sqlite3_migration
description: A package to manage SQLite3 migrations in Flutter.
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  sqlite3: ^2.7.2
  sqlite3_flutter_libs: ^0.5.29+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

