name: foundation
description: Building blocks for Boorusama
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  easy_localization: ^3.0.7
  easy_logger: ^0.0.2
  equatable: ^2.0.5
  fast_immutable_collections: ^11.0.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_riverpod: ^2.5.1
  fpdart: ^1.1.0
  hive: ^2.2.3
  intl: ^0.19.0
  jiffy: ^6.2.1
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

