name: foundation
description: Building blocks for Boorusama
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  equatable: ^2.0.5
  fast_immutable_collections: ^11.0.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  font_awesome_flutter: ^10.8.0
  fpdart: ^1.1.0
  hive_ce: ^2.12.0
  intl: ^0.20.2
  jiffy: ^6.2.1
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

